/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

public class FormMenuQueroLer extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuQueroLer
     */
    public FormMenuQueroLer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prox = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        Primeiro = new javax.swing.JTextField();
        Segundo = new javax.swing.JTextField();
        salvar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proxMouseClicked(evt);
            }
        });
        getContentPane().add(prox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 90, 30));

        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 110, 50));

        Primeiro.setBorder(null);
        getContentPane().add(Primeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 136, 100, 20));

        Segundo.setBorder(null);
        Segundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoActionPerformed(evt);
            }
        });
        getContentPane().add(Segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 136, 140, 20));

        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarMouseClicked(evt);
            }
        });
        getContentPane().add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 110, 50));

        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proxMouseClicked
        // TODO add your handling code here:
        new FormQueroLer2().setVisible(true);
    }//GEN-LAST:event_proxMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        // TODO add your handling code here:
        new FormTelaMenu().setVisible(true);
    }//GEN-LAST:event_voltarMouseClicked

    private void SegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoActionPerformed

    private void salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseClicked
        // TODO add your handling code here:
        if(Primeiro.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Digite o seu primeiro nome na primeira caixinha!");
            
        }else{
            String nome = Primeiro.getText();
            Segundo.setText(nome);
            Primeiro.setText(" ");
        } 
    }//GEN-LAST:event_salvarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuQueroLer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuQueroLer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuQueroLer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuQueroLer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuQueroLer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Primeiro;
    private javax.swing.JTextField Segundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel prox;
    private javax.swing.JLabel salvar;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
